//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Accumulation Time Averaged,Accumulation_Time_Averaged;Footer</string>
  <string>Averages Made,Averages_Made;Footer</string>
  <string>Mass Range Mode,Mass_Range_Mode;Footer</string>
  <string>Ion Polarity,Ion_Polarity;Header</string>
  <string>Manual MSN,Manual_MSn;Footer</string>
  <string>MRM,MRM;Footer</string>
  <string>Auto MS/MS,Auto_MSMS;Footer</string>
  <string>Averages,Averages;Footer</string>
  <string>Start Polarity,Start_Polarity;Footer</string>
  <string>Stop Polarity,Stop_Polarity;Footer</string>
  <string>Ready Polarity,Ready_Polarity;Footer</string>
  <string>ICC Target,ICC_Target;Footer</string>
  <string>Multiplier Gain Target,Multiplier_Gain_Target;Footer</string>
  <string>Scan Begin,Scan_Begin;Footer</string>
  <string>Scan End,Scan_End;Footer</string>
  <string>Target Mass,Target_Mass;Footer</string>
  <string>Compound Stability,Compound_Stability;Footer</string>
  <string>Trap Drive Level,Trap_Drive_Level;Footer</string>
  <string>Trap Drive,Trap_Drive;Footer</string>
  <string>ICC Actual,ICC_Actual;Footer</string>
  <string>Count of Scans,Scan_count;Footer</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LimpReportData {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LimpReportData"]));
            }
        }
    }
}
